apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  selector:
    app: inference  # Selects pods labeled with 'app: inference'
  ports:
    - name: port-8000  # Adding name for the first port
      protocol: TCP
      port: 8000  # Port exposed by the service
      targetPort: 8000  # Port on the Pods that traffic will be forwarded to
    - name: port-9090  # Adding name for the second port
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer  # Change the Service type to LoadBalancer
