apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  selector:
    app: inference  # Selects pods labeled with 'app: inference'
  ports:
    - protocol: TCP
      port: 8000  # Port exposed by the service
      targetPort: 8000  # Port on the Pods that traffic will be forwarded to
  type: ClusterIP  # Service type (can be ClusterIP, NodePort, LoadBalancer, etc.)