apiVersion: v1
kind: Service
metadata:
  name: beta-inference-service
spec:
  selector:
    app: beta-inference
  ports:
    - protocol: TCP
      port: 3002   # Port exposed externally
      targetPort: 8000   # Port your container is listening on
  type: ClusterIP
