version: '3'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8000/"]
      interval: 30s
      timeout: 5s
    network_mode: 'host'