version: '3'
services:
  tattletale-jurnal:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8000/"]
      interval: 30s
      timeout: 5s