apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfa-inference-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfa-inference
  template:
    metadata:
      labels:
        app: alfa-inference
    spec:
      containers:
      - name: inference-container
        image: mbiskho/tamlops-inference
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
