apiVersion: v1
kind: Service
metadata:
  name: alfa-inference-service
spec:
  selector:
    app: alfa-inference
  ports:
    - protocol: TCP
      port: 8000   # Port your container is listening on
      targetPort: 8000   # Port your container is listening on
      nodePort: 3031   # NodePort that will expose your service externally
  type: NodePort
