apiVersion: v1
kind: Service
metadata:
  name: alfa-inference-service
spec:
  selector:
    app: alfa-inference
  ports:
    - protocol: TCP
      port: 8000    # Port exposed externally
      targetPort: 8000   # Port your container is listening on
  type: ClusterIP
