apiVersion: apps/v1
kind: Deployment
metadata:
  name: bismakhomeini-trainning-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: bismakhomeini-trainning
  template:
    metadata:
      labels:
        app: bismakhomeini-trainning
    spec:
      volumes:
        - name: pvol-bismakhomeini
          persistentVolumeClaim:
            claimName: pvclaim-bismakhomeini
      containers:
        - name: bismakhomeini-trainning
          image: "mbiskho/tamlops-trainning" 
          command: ["/bin/sh"]
          args: ["-c", "python init.py"]
          volumeMounts:
            - mountPath: "/workspace"
              name: pvol-bismakhomeini
