apiVersion: v1
kind: Pod
metadata:
  name: bismakhomeini-trainning-pod
spec:
  restartPolicy: Never
  volumes:
    - name: pvol-bismakhomeini
      persistentVolumeClaim:
        claimName: pvclaim-bismakhomeini
  containers:
    - name: bismakhomeini-trainning
      image: "mbiskho/tamlops-trainning"  # Change this (Look up at NGC NVIDIA)
      command: ["/bin/sh"]
      # args: ["-c", "while true; do echo 'bismakhomeini-pod log'; sleep 10; done"]
      args: ["-c", "python init.py"]
      volumeMounts:
        - mountPath: "/workspace"
          name: pvol-bismakhomeini