apiVersion: v1
kind: Service
metadata:
  name: inference-loadbalancer-service
spec:
  selector:
    app: inference-loadbalancer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000  
  type: ClusterIP
