metrics:
  global:
    scrape_interval: 60s
  configs:
  - name: hosted-prometheus
    scrape_configs:
      - job_name: node
        static_configs:
        - targets: ['localhost:9100']
    global:
      external_labels:
        origin_prometheus: prometheus01
      remote_write:
      - url: https://prometheus-prod-18-prod-ap-southeast-0.grafana.net/api/prom/push
        basic_auth:
          username: 1193718
          password: glc_eyJvIjoiOTQ2OTQwIiwibiI6InN0YWNrLTc0MjkwMS1pbnRlZ3JhdGlvbi1pbmZlcmVuY2UiLCJrIjoiWjhHenFISjhWazR2N0k1TUwxNFQ0NThRIiwibSI6eyJyIjoicHJvZC1hcC1zb3V0aGVhc3QtMCJ9fQ==
s
